config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'stories#index'

  resources :stories do
    resources :comments
  end

  resources :comments do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
  has_many :comments, as: :commentable, dependent: :destroy
  belongs_to :user
end

app/models/story.rb
class Story < ApplicationRecord
  has_many :comments, as: :commentable, dependent: :destroy
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :stories
  has_many :comments
  
  def display_name
    email.split("@").first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_commentable
  before_action :authenticate_user!

  def create
    @comment = @commentable.comments.new(comment_params)
    @comment.user = current_user

    if @comment.save
      flash[:notice] = "comment 新建成功"
      redirect_back fallback_location: root_path
    else
      flash[:alert] =  "something wrong"
      redirect_back fallback_location: root_path
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end

  def find_commentable
    @commentable = Comment.find_by_id(params[:comment_id]) if params[:comment_id]
    @commentable = Story.find_by_id(params[:story_id]) if params[:story_id]
  end

end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :find_story_and_check_permission, only: [:edit, :update, :destroy]

  def index
    @stories = Story.all
  end

  def show
    @story = Story.find(params[:id])
    @comments = @story.comments.order("created_at DESC")
  end

  def new
    @story = Story.new
  end

  def edit
  end

  def create
    @story = Story.new(story_params)
    @story.user = current_user

    if @story.save
      flash[:notice] = "Story created successfully"
      redirect_to stories_path
    else
      render :new
    end
  end

  def update
    if @story.update(story_params)
      flash[:notice] = "Story updated successfully"
      redirect_to stories_path
    else
      render :edit
    end
  end

  def destroy
    @story.destroy
    flash[:alert] = "Story deleted"
    redirect_to stories_path
  end

  private

  def story_params
    params.require(:story).permit(:title, :url)
  end

  def find_story_and_check_permission
    @story = Story.find(params[:id])

    if current_user != @story.user
      flash[:warning] = "You have no permission."
      redirect_to root_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning" }.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch(key.to_sym, key) #=> value
  end

  def user_facing_flashes
    flash.to_hash.slice("alert", "notice", "warning") #=> hash
  end
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/comments/_comment.html.erb
<li class="list-unstyled replies">
  <div class="media">
    <div class="media-left">
      <% if comment.commentable_type == "Story" %>
        <img class="media-object img-circle img-40" src="/images/green-logo.png" alt="user default logo">
      <% else %>
        <img class="media-object img-circle img-30" src="/images/green-logo.png" alt="user default logo">
      <% end %>
    </div><!-- end media left -->

    <div class="media-body">
      <h4 class="media-heading"><%= comment.user.display_name %></h4>
      <p class="text-muted">Reply at: <%= comment.created_at.to_s(:long) %></p>
      <p><%= simple_format comment.body %></p>

      <p id="open-toggle-<%= comment.id %>" class="btn btn-link">reply</p>

      <!-- ===========reply form hide/show============ -->
      <div class="bg-success well-sm" id="comment-<%= comment.id %>">
        <%= form_for [comment, Comment.new] do |f| %>
          <div class="form-group">
            <%= f.text_area :body, placeholder: "say something ... ", class: "form-control", id: "textarea-#{comment.id}"  %>
          </div>

          <div class="form-group text-right">
            <span class="btn btn-default btn-xs" id="hide-toggle-<%= comment.id %>">Cancel</span>
            <%= f.submit "reply", class: "btn btn-primary" %>
          </div>
        <% end %>
      </div><!-- end well-sm -->
    </div><!-- end media body -->
  </div><!-- end media -->

  <ul>
    <%= render partial: "comments/comment", collection: comment.comments %>
  </ul>
</li>

<script>
  $(document).on("turbolinks:load", function(){
    // js for comment form hide/show
    $("#comment-<%= comment.id %>").hide();

    $("#open-toggle-<%= comment.id %>").click(function(){
      $("#comment-<%= comment.id %>").show();
      $("#textarea-<%= comment.id %>").focus();
    });

    $("#hide-toggle-<%= comment.id %>").click(function(){
      $("#comment-<%= comment.id %>").hide();
    })
  });
</script>

app/views/common/_flashes.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| %>
    <div class="alert alert-dismissible alert-<%= flash_class(key) %>">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= value %>
    </div>
  <% end %>
<% end %>

app/views/common/_footer.html.erb
<footer class="footer">
  <div class="container">
    <div class="row">
      <div class="col-sm-4">
        <p class="text-muted lead mgt10"><strong>Time now:</strong><br> <%= Time.now.to_s(:long) %></p>
      </div>
      <div class="col-sm-8">
        <ul class="list-unstyled text-center text-muted mgt10">
          <li><strong>外部链接</strong></li>
          <li class="active"><a href="https://github.com/cwy007/reddit-like-commenting-system" target="_blank">Source code <span class="sr-only">(current)</span></a></li>
          <li><a href="https://www.codementor.io/ruby-on-rails/tutorial/threaded-comments-polymorphic-associations" target="_blank">Reference</a></li>
          <li><a href="https://www.reddit.com/" target="_blank">Reddit website</a></li>
        </ul>
      </div>
    </div><!-- end row -->
  </div><!-- end container -->
</footer>

app/views/common/_navbar.html.erb
    <nav class="navbar navbar-inverse">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Reddit-like commenting system</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if !current_user %>
            <li><%= link_to "注册", new_user_registration_path %></li>
            <li><%= link_to "登录", new_user_session_path %></li>
            <% else %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                <img src="/images/default-profile.png" alt="default user logo" class="img-circle img-30" style="margin: -15px 0;" />
                <%= current_user.display_name %>
                <span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                <li><a href="/">Home</a></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to "登出", destroy_user_session_path, method: :delete %></li>
              </ul>
              <% end %>
            </li>
          </ul><!-- /.navbar-right -->
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container -->
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedditLikeCommentingSystem</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="shortcut icon" href="/images/favicon.ico">
  </head>

  <body>
    <%= render "common/navbar" %>
    <div class="container">
      <div class="content">
        <%= render "common/flashes" %>

        <%= yield %>
      </div>
    </div>
    <%= render "common/footer" %>
  </body>
</html>

app/views/stories/_form.html.erb
<%= form_for @story do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_area :title, placeholder: "Add a title", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :url %>
    <%= f.url_field :url, placeholder: "https://example.com", class: "form-control" %>
  </div>

  <%= f.submit "Submit", class: "btn btn-primary" %>
  <%= link_to "Cancel", stories_path, class: "btn btn-link" %>
<% end %>

app/views/stories/_story.html.erb
<tr>
  <td><%= link_to story.title, story.url, target: "_blank" %></td>
  <td><%= story.user.email %></td>
  <td>
    <% from_comment_show ||= false %>
    <% if from_comment_show %>
      <% if current_user && story.user == current_user %>
        <%= link_to "Edit", edit_story_path(story), class: "btn btn-primary btn-xs" %>
        <%= link_to "Delete", story_path(story), method: :delete, class: "btn btn-danger btn-xs" %>
      <% end %>
    <% else %>
      <%= link_to "Comments", story, class: "btn btn-info btn-xs" %>
    <% end %>
  </td>
</tr>

app/views/stories/edit.html.erb
<h1 class="text-center text-warning">Edit Story</h1>

<%= render "form" %>

app/views/stories/index.html.erb
<h1 class="text-center text-danger">Stories List</h1>

<div class="text-right" style="margin-bottom: 30px;">
  <%= link_to "New Story", new_story_path, class: "btn btn-primary" %>
</div>

<table class="table">
  <tbody>
    <thead>
      <tr>
        <th>Story link</th>
        <th>User</th>
        <th>action</th>
      </tr>
    </thead>
    <tbody>
      <%= render @stories %>
    </tbody>
  </tbody>
</table>

app/views/stories/new.html.erb
<h2 class="text-center text-success">New comment</h2>

<%= render "form" %>

app/views/stories/show.html.erb
<div class="story-show-page">
  <h1 class="text-right">
    <%= link_to stories_path, class: "btn btn-default" do%>
    Back &rarr;
    <% end %>
  </h1>

  <table class="table">
    <%= render @story, from_comment_show: true %>
  </table>

  <h1 class="text-center text-info" style="margin: 60px 0 50px;">Comments</h1>

  <div class="" style="border: none;">
    <%= form_for [@story, Comment.new] do |f| %>
      <%= f.text_area :body, placeholder: "Add a comment ...", class: "form-control", id: "new-comment" %>
      <div class="submit text-right">
        <button type="button" id="cancel">Cancel</button>
        <%= f.submit "Submit", class:"fsubmit" %>
      </div>
    <% end %><!-- end new comment --->
  </div>

  <hr>

  <ul>
    <%= render partial: "comments/comment", collection: @comments %>
  </ul><!-- end render comment partial -->
</div>

<script type="text/javascript">
  $(document).on("turbolinks:load", function(){
    $(".submit").hide();

    $("#new-comment").click(function(){
      $(".submit").show();
      $("#new-comment").css("height","84px");
    });

    $("#cancel").click(function(){
      $(".submit").hide();
      $("#new-comment").val("");
      $("#new-comment").css("height","54px");
    })
  })
</script>